name: occenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flask=3.0.3
  - numpy
  - pythonocc-core=7.6.2
  - pyopengl=3.1.6
  - trimesh=4.6.8
  - gunicorn
  - pip
  - pip:
      - blinker==1.8.2
      - click==8.1.8
      - colorama==0.4.6
      - git-filter-repo==2.47.0
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - MarkupSafe==2.1.5
      - python-utils==3.8.2
      - typing_extensions==4.13.2
